#!/usr/bin/env bash
# This script echos "Best School" ten times, with a special case on the 9th iteration

n=1
while [ $n -le 10 ]; do
    if [ $n -eq 9 ]; then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    ((n++))
done

